### ISSUE TITLE
Install/Run Instructions

### ISSUE THREAD

**Issue by agruszynski** [anuraj/MVCAngularCRUDExample#1]
Do you have install or run instructions for this seed project?  I notice the ClientApp isn't part of the .Net project.  What sort of pattern are you using and what procedures do you intend developers to use when developing from this seed?  Do you run both the WebAPI app and also "ng serve" for development?  That would require some cors or proxy setup.  I don't see how running this only in VS(not using ng serve) is possible with HMR.  Hope you can shed some light on your intentions.

**Comment by anuraj** [comment]
-  I notice the ClientApp isn't part of the .Net project - Yes I didn't included the angular project into my VS solution / project.
- Do you run both the WebAPI app and also "ng serve" for development? - No, I have modified the project file (https://github.com/anuraj/MVCAngularCRUDExample/commit/0ac26397bc7dc1f769379f0b2c1360c42aaee6f6#diff-bc4f9cd406d7279d4b85cfeaff4a5403R190 and https://github.com/anuraj/MVCAngularCRUDExample/commit/0ac26397bc7dc1f769379f0b2c1360c42aaee6f6#diff-bc4f9cd406d7279d4b85cfeaff4a5403R193) for doing a ng build while running the application.
- Hope you can shed some light on your intentions - :) In the current project I am working, we were using Angular 5 with MVC. But I couldn't find any tutorial on how to deploy it. So I wrote one over [here](https://dotnetthoughts.net/how-to-use-angular4-wth-aspnet-mvc/). Based on feedback I wrote a sample app, which I could deploy it live, so I wrote this application. Unfortunately I am a newbie in Angular 5, so I don't know much about HMR.

**Comment by stherrienaspnet** [comment]
Hello this seems to be really what I'm looking for. But when i try running your github code it cannot open the page on localhost. Maybe I'm dooing something wrong. Could you give me some info about how to run the web site?  Thanks in advance

**Comment by anuraj** [comment]
Can you share more details? Like are you getting any script errors? or your not getting the Home/Index page?

**Comment by Djaw** [comment]
Could this example be translated for use with MVC4?
The current app I'm working on uses MVC4 wondering if there would be a communication issue between the 2 versions.

**Comment by Djaw** [comment]
Is there a reason you got rid of the shared layout?

**Comment by anuraj** [comment]
@Djaw I think we can use it with ASP.NET MVC 4. I never tested it, but it should ideally work with ASP.NET MVC 4. No. There is no particular reason not to use shared layout. I tried to make it simple that is the only reason.
